name: stacked_sheet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.1.5 <4.0.0"

dependencies:
    carousel_slider: ^4.2.1
    cupertino_icons: ^1.0.2
    flutter:
        sdk: flutter
    flutter_gen: ^5.3.2
    google_fonts: ^6.1.0

dev_dependencies:
    build_runner: ^2.4.6
    flutter_gen_runner: ^5.3.2
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter_gen:
  output: lib/layers/presentation/gen

flutter:
    uses-material-design: true
    assets:
        - assets/images/
