name: stacked_sheet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animations: ^2.0.8
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_gen: ^5.3.2
  go_router: ^12.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/layers/presentation/gen

flutter:
  uses-material-design: true
  assets:
    - assets/images/
